version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps
  build:
    commands:
      - echo Building the Angular app...
      - npx ng build --configuration=production

artifacts:
  files:
    - '**/*'
  base-directory: dist/awsapp2/browser
  discard-paths: no
